apiVersion: v1
kind: Service
metadata:
  name: tinygpt-postgres
  namespace: tinygpt
spec:
  selector:
    app: tinygpt-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
