apiVersion: v1
kind: Service
metadata:
  name: tinygpt-api-nodeport
  namespace: tinygpt
spec:
  type: NodePort
  selector:
    app: tinygpt-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30080
